"use client";
import { useEffect, useState } from "react";
import { Loader2, RefreshCw, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Health = { source: string; label: string; status: string; expiresAt: string | null; remainingDays: number | null; checkedAt: string; lastError: string | null; lastValidSource: string | null };
const sources = ["olsera", "ayo-booking", "ayo-payment-events"] as const;
const label: Record<(typeof sources)[number], string> = { olsera: "Olsera Sales", "ayo-booking": "AYO Booking", "ayo-payment-events": "AYO Payment Events" };
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta" }).format(new Date());

export function PrivateIntegrationMonitor() {
  const [health, setHealth] = useState<Health[] | null>(null); const [source, setSource] = useState<(typeof sources)[number]>("ayo-booking"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [busy, setBusy] = useState(false); const [result, setResult] = useState<Record<string, unknown> | null>(null);
  const load = async () => { const res = await fetch("/api/private/integration-monitor", { cache: "no-store" }); if (res.ok) { const data = await res.json(); setHealth(data.tokenHealth); } else setHealth(null); };
  useEffect(() => { const end = today(); const date = new Date(`${end}T00:00:00Z`); date.setUTCDate(date.getUTCDate() - 29); setFrom(date.toISOString().slice(0, 10)); setTo(end); void load(); }, []);
  const audit = async (action: "check" | "repair") => { const message = source === "olsera" ? "Tutup hanya order dan item yang terdeteksi hilang pada audit terakhir. Data existing tidak akan dihapus atau ditimpa." : "Tutup hanya data yang terdeteksi hilang pada audit terakhir. Data existing tidak akan dihapus atau ditimpa."; if (action === "repair" && !window.confirm(message)) return; setBusy(true); try { const res = await fetch("/api/private/integration-monitor", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source, startDate: from, endDate: to, action }) }); setResult(await res.json()); } finally { setBusy(false); } };
  if (health === null) return null;
  return <section className="mt-6 rounded-xl border border-cyan-300/20 bg-cyan-950/20 p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-100">Monitoring Integritas Data</h2><p className="mt-1 text-sm text-slate-400">Hanya metadata aman; token dan credential tidak pernah ditampilkan.</p></div><Button type="button" variant="outline" onClick={() => void load()} disabled={busy}><RefreshCw className="h-4 w-4" /> Periksa Sekarang</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{health.map((item) => <div key={item.source} className="rounded-lg border border-white/10 bg-black/10 p-3"><div className="flex items-center justify-between gap-2"><b className="text-sm text-slate-100">{item.label}</b><span className="text-xs font-semibold text-cyan-200">{item.status}</span></div><p className="mt-2 text-xs text-slate-400">{item.expiresAt ? `Kedaluwarsa: ${new Date(item.expiresAt).toLocaleDateString("id-ID")} (${item.remainingDays} hari)` : "Expiry tidak diketahui"}</p><p className="text-xs text-slate-500">Sumber valid: {item.lastValidSource ?? "Belum ada"}</p>{item.lastError && <p className="text-xs text-rose-300">{item.lastError}</p>}</div>)}</div><div className="mt-4 border-t border-white/10 pt-4"><h3 className="text-sm font-semibold text-slate-100">Cek &amp; Tutup Gap Data</h3><div className="mt-3 grid gap-3 sm:grid-cols-4"><select aria-label="Sumber audit" value={source} onChange={(e) => setSource(e.target.value as typeof source)} className="rounded-md border border-white/10 bg-black/20 px-3 py-2 text-sm text-slate-100">{sources.map((value) => <option key={value} value={value}>{label[value]}</option>)}</select><Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} disabled={busy}/><Input type="date" value={to} onChange={(e) => setTo(e.target.value)} disabled={busy}/><div className="flex gap-2"><Button type="button" onClick={() => void audit("check")} disabled={busy || !from || !to}>{busy && <Loader2 className="h-4 w-4 animate-spin"/>}Cek Gap</Button><Button type="button" variant="outline" onClick={() => void audit("repair")} disabled={busy || (result as { status?: string } | null)?.status !== "GAP_FOUND"}>Tutup Gap</Button></div></div>{result && <pre className="mt-3 overflow-auto rounded-md bg-black/20 p-3 text-xs text-slate-300">{JSON.stringify(result, null, 2)}</pre>}</div></section>;
}
