export type FebruaryHistoricalRow = { product:string; group:string; sku:string|null; opening:number; incoming:number; returnQty:number; salesQty:number; outgoingQty:number; closing:number };
export const FEBRUARY_HISTORICAL_SOURCE = {
  "sold": [
    {
      "product": "NESTLE PURE LIFE 1500ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 540,
      "returnQty": 0,
      "salesQty": 186,
      "outgoingQty": 0,
      "closing": 354
    },
    {
      "product": "NESTLE PURE LIFE 600ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 408,
      "returnQty": 0,
      "salesQty": 192,
      "outgoingQty": 0,
      "closing": 216
    },
    {
      "product": "POCARI SWEAT PET 500 ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 360,
      "returnQty": 0,
      "salesQty": 121,
      "outgoingQty": 0,
      "closing": 239
    },
    {
      "product": "POCARI SWEAT PET 900ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 150,
      "returnQty": 0,
      "salesQty": 58,
      "outgoingQty": 0,
      "closing": 92
    },
    {
      "product": "POCARI ION WATER 500ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 240,
      "returnQty": 0,
      "salesQty": 92,
      "outgoingQty": 0,
      "closing": 148
    },
    {
      "product": "SOY JOY MULTI VARIANT",
      "group": "SNACK",
      "sku": null,
      "opening": 0,
      "incoming": 60,
      "returnQty": 0,
      "salesQty": 28,
      "outgoingQty": 0,
      "closing": 32
    },
    {
      "product": "BOLA HEAD PRO ISI 3",
      "group": "BOLA PADEL",
      "sku": null,
      "opening": 0,
      "incoming": 24,
      "returnQty": 0,
      "salesQty": 3,
      "outgoingQty": 0,
      "closing": 21
    },
    {
      "product": "BOLA PADEL HEAD PRO S+ ISI 3",
      "group": "BOLA PADEL",
      "sku": null,
      "opening": 0,
      "incoming": 24,
      "returnQty": 0,
      "salesQty": 6,
      "outgoingQty": 0,
      "closing": 18
    },
    {
      "product": "BOLA PADEL ODEA",
      "group": "BOLA PADEL",
      "sku": null,
      "opening": 96,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 30,
      "outgoingQty": 0,
      "closing": 66
    },
    {
      "product": "Bullpadel Indiga Discover PWR 2025",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 0
    },
    {
      "product": "GRIP LI-NING",
      "group": "GRIP",
      "sku": null,
      "opening": 0,
      "incoming": 30,
      "returnQty": 0,
      "salesQty": 11,
      "outgoingQty": 0,
      "closing": 19
    },
    {
      "product": "YONEX LADIES SKORT #SKL-P061-2846-SOLID-S",
      "group": "SKORT WANITA",
      "sku": null,
      "opening": 24,
      "incoming": 9,
      "returnQty": 0,
      "salesQty": 7,
      "outgoingQty": 0,
      "closing": 26
    },
    {
      "product": "YONEX SHORTS MEN # SM-J035-2906-RW1-S",
      "group": "CELANA PRIA",
      "sku": null,
      "opening": 24,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 9,
      "outgoingQty": 0,
      "closing": 15
    },
    {
      "product": "YONEX MEN SOCKS SSM-1285ID-MP6-S",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 30,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 2,
      "outgoingQty": 0,
      "closing": 28
    },
    {
      "product": "YONEX MENS SHORTS # SM-P061-3085-RW2-S",
      "group": "CELANA PRIA",
      "sku": null,
      "opening": 12,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 2,
      "outgoingQty": 0,
      "closing": 10
    },
    {
      "product": "YONEX POLO MEN # PM-P064-2736-EASY4-S",
      "group": "BAJU PRIA",
      "sku": null,
      "opening": 12,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 3,
      "outgoingQty": 0,
      "closing": 9
    },
    {
      "product": "YONEX MEN POLO T-SHIRT # PM-P064-2626-EASY3-S",
      "group": "BAJU PRIA",
      "sku": null,
      "opening": 18,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 12,
      "outgoingQty": 0,
      "closing": 6
    },
    {
      "product": "YONEX MEN SOCKS SSM-1255ID-MP6-SR",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 10,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 9
    },
    {
      "product": "BULLPADEL HACK 04 COMFORT 2026-355-360 GREY/GREEN",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 0
    },
    {
      "product": "YONEX LADIES SOCKS # SSL-2860R-S",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 8,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 7
    },
    {
      "product": "YONEX SOCKS SSM-1055ID-MP6-SR",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 30,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 29
    },
    {
      "product": "YONEX  WOMEN CAP SILICON",
      "group": "TOPI",
      "sku": null,
      "opening": 60,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 59
    },
    {
      "product": "Siux Beat Hybrid 2",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 0
    },
    {
      "product": "YONEX MEN SOCKS SSM-1284ID-MP6-S",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 35,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 34
    },
    {
      "product": "Siux Beat Hybrid Air 2",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 0
    },
    {
      "product": "YONEX LADIES SOCKS # SSL-2859R-S",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 10,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 9
    },
    {
      "product": "Bullpadel Indiga Mundial Argentina LTD 1988",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 3,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "Bullpadel Sniper 2.0 Power Black 2026",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 2,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "YONEX MEN SOCKS SSM-1855ID-MP6-SR",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 30,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 29
    },
    {
      "product": "YONEX MALAYSIA OPEN THERMO FLASK # TF-Y037-850-004-25-S",
      "group": "THERMOFLASK",
      "sku": null,
      "opening": 30,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 29
    },
    {
      "product": "RAKET PADEL ADIDAS 2026 MATCH",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 0,
      "incoming": 4,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 4
    }
  ],
  "overall": [
    {
      "product": "YONEX MEN SOCKS SSM-1285ID-MP6-S",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 30,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 2,
      "outgoingQty": 0,
      "closing": 28
    },
    {
      "product": "YONEX MEN SOCKS SSM-1255ID-MP6-SR",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 10,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 9
    },
    {
      "product": "YONEX LADIES SOCKS # SSL-2860R-S",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 8,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 7
    },
    {
      "product": "YONEX SOCKS SSM-1055ID-MP6-SR",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 30,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 29
    },
    {
      "product": "YONEX MEN SOCKS SSM-1284ID-MP6-S",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 35,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 34
    },
    {
      "product": "YONEX LADIES SOCKS # SSL-2859R-S",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 10,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 9
    },
    {
      "product": "YONEX MEN SOCKS SSM-1855ID-MP6-SR",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 30,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 29
    },
    {
      "product": "YONEX MEN SOCKS SSM-1086ID-MP6-S",
      "group": "KAOS KAKI",
      "sku": null,
      "opening": 20,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 20
    },
    {
      "product": "YONEX SHORTS MEN # SM-J035-2906-RW1-S",
      "group": "CELANA PRIA",
      "sku": null,
      "opening": 24,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 9,
      "outgoingQty": 0,
      "closing": 15
    },
    {
      "product": "YONEX MENS SHORTS # SM-P061-3085-RW2-S",
      "group": "CELANA PRIA",
      "sku": null,
      "opening": 12,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 2,
      "outgoingQty": 0,
      "closing": 10
    },
    {
      "product": "YONEX LADIES SKORT #SKL-P061-2846-SOLID-S",
      "group": "SKORT WANITA",
      "sku": null,
      "opening": 24,
      "incoming": 9,
      "returnQty": 0,
      "salesQty": 7,
      "outgoingQty": 0,
      "closing": 26
    },
    {
      "product": "YONEX POLO MEN # PM-P064-2736-EASY4-S",
      "group": "BAJU PRIA",
      "sku": null,
      "opening": 12,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 3,
      "outgoingQty": 0,
      "closing": 9
    },
    {
      "product": "YONEX MEN POLO T-SHIRT # PM-P064-2626-EASY3-S",
      "group": "BAJU PRIA",
      "sku": null,
      "opening": 18,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 12,
      "outgoingQty": 0,
      "closing": 6
    },
    {
      "product": "YONEX MALAYSIA OPEN THERMO FLASK # TF-Y037-850-004-25-S",
      "group": "THERMOFLASK",
      "sku": null,
      "opening": 30,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 29
    },
    {
      "product": "Bullpadel Sniper 2.0 Power Black 2026",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 2,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "Bullpadel Sniper 2.0 Power Light Blue 2026",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 2,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "Bullpadel Sniper 2.0 Oil Petroleo 2026",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "Bullpadel Indiga Discover PWR 2025",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 0
    },
    {
      "product": "Bullpadel Indiga Mundial Argentina LTD 1988",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 3,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 2
    },
    {
      "product": "Nox X ONE Black",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "Siux Beat Hybrid 2",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 0
    },
    {
      "product": "Siux Beat Hybrid Air 2",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 0
    },
    {
      "product": "BULLPADEL IONIC CONTROL 25-365-375G NAVY",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL K2 POWER 25-360-370G NAVY",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL BP10 EVO 25-360-370G GREY",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL FLOW LIGHT 25-350-360G RED",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL INDIGA PWR 25-360-370G WHITE",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL INDIGA CTR 25-360-370G GREEN",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL INDIGA W 25-350-360G WHITE",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL HACK JR 25-335-345G GREEN",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL VERTEX JR 25-335-345G BLACK",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL HACK 04 COMFORT 2026-355-360 GREY/GREEN",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 0
    },
    {
      "product": "BULLPADEL VERTEX 05 COMFORT 2026-360-370 BLACK/BLUE",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL XPLO COMFORT 2026-360-370 BLACK/GREY",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "BULLPADEL FLOW LEGEND 2026-345-350 GREY/WHITE",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 1,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 1
    },
    {
      "product": "RAKET PADEL ADIDAS 2026 MATCH",
      "group": "RAKET PADEL",
      "sku": null,
      "opening": 4,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 4
    },
    {
      "product": "BOLA HEAD PRO ISI 3",
      "group": "BOLA PADEL",
      "sku": null,
      "opening": 0,
      "incoming": 24,
      "returnQty": 0,
      "salesQty": 3,
      "outgoingQty": 0,
      "closing": 21
    },
    {
      "product": "BOLA PADEL HEAD PRO S+ ISI 3",
      "group": "BOLA PADEL",
      "sku": null,
      "opening": 0,
      "incoming": 24,
      "returnQty": 0,
      "salesQty": 6,
      "outgoingQty": 0,
      "closing": 18
    },
    {
      "product": "BOLA PADEL ODEA",
      "group": "BOLA PADEL",
      "sku": null,
      "opening": 96,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 30,
      "outgoingQty": 0,
      "closing": 66
    },
    {
      "product": "GRIP LI-NING",
      "group": "GRIP",
      "sku": null,
      "opening": 0,
      "incoming": 30,
      "returnQty": 0,
      "salesQty": 11,
      "outgoingQty": 0,
      "closing": 19
    },
    {
      "product": "GRIP YONEX AC102",
      "group": "GRIP",
      "sku": null,
      "opening": 0,
      "incoming": 60,
      "returnQty": 0,
      "salesQty": 0,
      "outgoingQty": 0,
      "closing": 60
    },
    {
      "product": "NESTLE PURE LIFE 1500ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 540,
      "returnQty": 0,
      "salesQty": 186,
      "outgoingQty": 0,
      "closing": 354
    },
    {
      "product": "NESTLE PURE LIFE 600ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 408,
      "returnQty": 0,
      "salesQty": 192,
      "outgoingQty": 0,
      "closing": 216
    },
    {
      "product": "POCARI SWEAT PET 500 ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 360,
      "returnQty": 0,
      "salesQty": 121,
      "outgoingQty": 0,
      "closing": 239
    },
    {
      "product": "POCARI SWEAT PET 900ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 150,
      "returnQty": 0,
      "salesQty": 58,
      "outgoingQty": 0,
      "closing": 92
    },
    {
      "product": "POCARI ION WATER 500ML",
      "group": "MINUMAN",
      "sku": null,
      "opening": 0,
      "incoming": 240,
      "returnQty": 0,
      "salesQty": 92,
      "outgoingQty": 0,
      "closing": 148
    },
    {
      "product": "SOY JOY MULTI VARIANT",
      "group": "SNACK",
      "sku": null,
      "opening": 0,
      "incoming": 60,
      "returnQty": 0,
      "salesQty": 28,
      "outgoingQty": 0,
      "closing": 32
    },
    {
      "product": "YONEX  WOMEN CAP SILICON",
      "group": "TOPI",
      "sku": null,
      "opening": 60,
      "incoming": 0,
      "returnQty": 0,
      "salesQty": 1,
      "outgoingQty": 0,
      "closing": 59
    }
  ]
} as const;
