import "server-only";
import { getAccounts, getBalanceSheet, getCashFlow, getLedgerDetail, getLedgerSummary, getProfitLoss } from "./olsera-financial-client";
import { deduplicateFinancialAccounts, normalizeAccounts, normalizeBalanceSheetPayload, normalizeCashFlowPayload, normalizeLedgerDetailPayload, normalizeLedgerSummaryPayload, normalizeProfitLossPayload, validatePeriod } from "./olsera-financial-core";
import { bulkUpsertLedgerEntries, createFinancialSyncRun, getFinancialSyncRun, updateFinancialSyncRun, upsertAccounts, upsertMonthlyReport } from "./olsera-financial-store";

const reportTypes = ["balance-sheet", "profit-loss", "cash-flow", "ledger-summary"] as const;
function safeRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }
function periodParts(period: string) { return { year: Number(period.slice(0, 4)), month: Number(period.slice(5)) }; }
function validation(type: string, normalized: any): { validated: boolean; note: string | null } { if (type === "balance-sheet") return { validated: normalized.totals.balanced === true, note: normalized.totals.balanced ? null : "Neraca tidak balance." }; if (type === "profit-loss") return { validated: normalized.totals.grossProfitValid && normalized.totals.netProfitValid, note: normalized.totals.grossProfitValid && normalized.totals.netProfitValid ? null : "Formula laba rugi tidak valid." }; if (type === "cash-flow") return { validated: normalized.totals.activityTotalValid && normalized.totals.endingCashValid, note: normalized.totals.activityTotalValid && normalized.totals.endingCashValid ? null : "Formula arus kas tidak valid." }; return { validated: normalized.length === 85, note: normalized.length === 85 ? null : `Jumlah akun ${normalized.length}, diharapkan 85.` }; }
export async function startFinancialSync(year: unknown, month: unknown) { const period = validatePeriod(String(year), String(month)); const { year: y, month: m } = periodParts(period); const pages = await getAccounts(y, m); const accounts = deduplicateFinancialAccounts(normalizeAccounts(pages[0]), normalizeAccounts(pages[1])); const codes = accounts.map((row: any) => String(row.account_code ?? row.account_no ?? row.code ?? "")).filter(Boolean); await upsertAccounts(accounts); return createFinancialSyncRun(period, codes); }
export async function stepFinancialSync(runId: string) { const run = await getFinancialSyncRun(runId); if (!run) throw new Error("Sync run tidak ditemukan."); if (run.status === "success") return run; if (run.phase === "monthly-reports") { const [balanceRaw, profitRaw, cashRaw, ledgerRaw] = await Promise.all([getBalanceSheet(run.period), getProfitLoss(run.period), getCashFlow(run.period), getLedgerSummary(run.period)]); const reports = [["balance-sheet", normalizeBalanceSheetPayload(balanceRaw), balanceRaw, "account/balancenew"], ["profit-loss", normalizeProfitLossPayload(profitRaw), profitRaw, "account/gainloss"], ["cash-flow", normalizeCashFlowPayload(cashRaw), cashRaw, "account/cashflowstatement"], ["ledger-summary", normalizeLedgerSummaryPayload(ledgerRaw), ledgerRaw, "account/ledger2"]] as const; for (const [reportType, normalizedPayload, rawPayload, sourceEndpoint] of reports) { const result = validation(reportType, normalizedPayload); await upsertMonthlyReport({ period: run.period, year: periodParts(run.period).year, month: periodParts(run.period).month, reportType, normalizedPayload: safeRecord(normalizedPayload), rawPayload: safeRecord(rawPayload), sourceEndpoint, currency: "IDR", validated: result.validated, validationNote: result.note }); } return updateFinancialSyncRun(runId, { phase: "ledger-details", reportsCompleted: [...reportTypes], status: "running" }); }
 if (run.phase === "ledger-details") { const batch = run.accountCodes.slice(run.accountCursor, run.accountCursor + 4); let records = 0; let failed: string | null = null; for (const code of batch) { try { const raw = await getLedgerDetail(run.period, code); const normalized = normalizeLedgerDetailPayload(raw, code); await bulkUpsertLedgerEntries(code, run.period, normalized.entries as unknown as Array<Record<string, unknown>>); records += normalized.totalRecords; } catch { failed = "Sebagian Buku Besar Detail gagal disinkronkan."; } } const cursor = run.accountCursor + batch.length; return updateFinancialSyncRun(runId, { accountCursor: cursor, accountsProcessed: Math.min(cursor, run.accountCodes.length), recordsProcessed: run.recordsProcessed + records, status: failed ? "partial" : cursor >= run.accountCodes.length ? "success" : "running", phase: cursor >= run.accountCodes.length ? "completed" : "ledger-details", errorMessage: failed, completedAt: cursor >= run.accountCodes.length ? new Date() : null }); }
 return run;
}
export async function getFinancialSyncStatus(runId: string) { const run = await getFinancialSyncRun(runId); if (!run) return null; const total = run.accountCodes.length; return { status: run.status, period: run.period, phase: run.phase, progress: { accountsTotal: total, accountsProcessed: run.accountsProcessed, recordsProcessed: run.recordsProcessed, percentage: total ? Math.round((run.accountsProcessed / total) * 100) : 0 }, message: run.errorMessage ?? (run.status === "success" ? "Sinkronisasi selesai." : "Sinkronisasi berjalan."), completedAt: run.completedAt?.toISOString() ?? null }; }
