// @ts-nocheck
import "server-only";
import { createHash } from "node:crypto";
import { collections, withMongo, type OlseraFinancialMonthlyReportDocument } from "./mongodb";
import type { FinancialTestCollections } from "./olsera-financial-test-db";
const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex").slice(0, 32);
const storeId = () => { const value = Number(process.env.OLSERA_INTERNAL_STORE_ID); if (!Number.isInteger(value) || value <= 0) throw new Error("Konfigurasi store laporan keuangan tidak valid."); return value; };
export type FinancialStoreContext = FinancialTestCollections;
async function financialCollections(context?: FinancialStoreContext) { if (context) return { reports: context.reports, accounts: context.accounts, ledger: context.ledger, logs: context.logs }; const c = await collections(); return { reports: c.olseraFinancialMonthlyReports, accounts: c.olseraFinancialAccounts, ledger: c.olseraFinancialLedgerEntries, logs: c.olseraFinancialSyncLogs }; }
export const monthlyReportId = (id: number, period: string, type: string) => `${id}:${period}:${type}`;
export const accountDocumentId = (id: number, row: Record<string, unknown>) => `${id}:account:${row.account_id ?? row.id ?? row.account_code ?? row.account_no ?? hash(row)}`;
export const ledgerEntryId = (id: number, period: string, code: string, row: Record<string, unknown>) => `${id}:${period}:${code}:${row.id ?? hash({ transactionNo: row.transaction_no, date: row.transaction_date, debit: row.debit ?? row.fdebit, credit: row.credit ?? row.fcredit, raw: row })}`;
export async function upsertMonthlyReport(input: Omit<OlseraFinancialMonthlyReportDocument, "_id" | "storeId" | "createdAt" | "updatedAt" | "syncedAt">, context?: FinancialStoreContext) { return withMongo(async () => { const { reports } = await financialCollections(context); const id = monthlyReportId(storeId(), input.period, input.reportType), now = new Date(); await reports.updateOne({ _id: id }, { $set: { ...input, storeId: storeId(), syncedAt: now, updatedAt: now }, $setOnInsert: { _id: id, createdAt: now } }, { upsert: true }); }); }
export async function upsertAccounts(rows: unknown[], context?: FinancialStoreContext) { return withMongo(async () => { const { accounts } = await financialCollections(context); const id = storeId(), now = new Date(); for (const value of rows) { const row = value && typeof value === "object" ? value as Record<string, unknown> : {}; const _id = accountDocumentId(id, row); await accounts.updateOne({ _id }, { $set: { _id, storeId: id, accountId: (row.account_id ?? row.id ?? null) as string | number | null, accountCode: String(row.account_code ?? row.account_no ?? row.code ?? "") || null, accountName: String(row.account_name ?? row.name ?? "") || null, classification: String(row.classification ?? row.class ?? "") || null, parentId: (row.parent_id ?? null) as string | number | null, isActive: row.is_active !== false, rawPayload: row, syncedAt: now, updatedAt: now }, $setOnInsert: { createdAt: now } }, { upsert: true }); } }); }
export async function bulkUpsertLedgerEntries(accountCode: string, period: string, entries: Array<Record<string, unknown>>, context?: FinancialStoreContext) { return withMongo(async () => { const { ledger } = await financialCollections(context); const id = storeId(), now = new Date(); if (!entries.length) return; await ledger.bulkWrite(entries.map((row) => { const _id = ledgerEntryId(id, period, accountCode, row); return { updateOne: { filter: { _id }, update: { $set: { _id, storeId: id, period, accountCode, accountName: row.accountName ?? null, transactionDate: row.transactionDate ?? null, formattedTransactionDate: row.formattedTransactionDate ?? null, transactionNo: row.transactionNo ?? null, description: row.description ?? null, debit: Number(row.debit ?? 0), credit: Number(row.credit ?? 0), balance: row.balance == null ? null : Number(row.balance), isOpeningBalance: row.isOpeningBalance === true, rawPayload: row.rawPayload ?? row, syncedAt: now, updatedAt: now }, $setOnInsert: { createdAt: now } }, upsert: true } }; }), { ordered: false }); }); }
export async function createFinancialSyncRun(period: string, accountCodes: string[], context?: FinancialStoreContext) { return withMongo(async () => { const { logs } = await financialCollections(context); const id = `financial:${storeId()}:${period}`, now = new Date(); const run = { _id: id, storeId: storeId(), period, status: "running" as const, phase: "monthly-reports" as const, accountCursor: 0, accountCodes, reportsCompleted: [], recordsProcessed: 0, accountsProcessed: 0, errorMessage: null, startedAt: now, updatedAt: now, completedAt: null }; await logs.updateOne({ _id: id }, { $set: run }, { upsert: true }); return run; }); }
export async function getFinancialSyncRun(runId: string, context?: FinancialStoreContext) { return withMongo(async () => (await financialCollections(context)).logs.findOne({ _id: runId })); }
export async function updateFinancialSyncRun(runId: string, patch: Record<string, unknown>, context?: FinancialStoreContext) { return withMongo(async () => (await financialCollections(context)).logs.findOneAndUpdate({ _id: runId }, { $set: { ...patch, updatedAt: new Date() } }, { returnDocument: "after" })); }
