import "server-only";
import { mapFinancialError, validatePeriod } from "./olsera-financial-core";
export type FinancialResource = "list" | "balancenew" | "gainloss" | "cashflowstatement" | "ledger2" | "ledger/detail";
export class FinancialClientError extends Error { constructor(public readonly safe: { status: string; message: string }) { super(safe.message); } }
function config() { return { base: process.env.OLSERA_INTERNAL_BASE_URL, token: process.env.OLSERA_INTERNAL_TOKEN, storeId: process.env.OLSERA_INTERNAL_STORE_ID, slug: process.env.OLSERA_INTERNAL_STORE_SLUG }; }
function ensureConfig() { const c = config(); if (!c.base || !c.token || !c.storeId || !c.slug) throw new FinancialClientError({ status: "not-configured", message: "Koneksi laporan keuangan Olsera belum dikonfigurasi." }); return c as { base: string; token: string; storeId: string; slug: string }; }
export function buildFinancialUrl(resource: FinancialResource): string { const c = ensureConfig(); const base = c.base.replace(/\/+$/, ""); const slug = c.slug.replace(/^\/+|\/+$/g, ""); return `${base}/api/${slug}/admin/v1/id/account/${resource}`; }
async function request(resource: FinancialResource, params: Record<string, string>) { const c = ensureConfig(); const url = new URL(buildFinancialUrl(resource)); for (const [key, value] of Object.entries(params)) url.searchParams.set(key, value); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 10000); try { const response = await fetch(url, { headers: { Authorization: `Bearer ${c.token}`, Accept: "application/json" }, signal: controller.signal, cache: "no-store" }); if (!response.ok) throw new FinancialClientError(mapFinancialError(response.status)); return await response.json(); } catch (error) { if (error instanceof FinancialClientError) throw error; throw new FinancialClientError({ status: "unreachable", message: "Tidak dapat terhubung ke server Olsera." }); } finally { clearTimeout(timer); } }
export async function getFinancialStatus() { try { const baseline = process.env.OLSERA_FINANCIAL_BASELINE_PERIOD || "2026-02"; const match = /^(\d{4})-(\d{1,2})$/.exec(baseline); if (!match) throw new FinancialClientError({ status: "not-configured", message: "Koneksi laporan keuangan Olsera belum dikonfigurasi." }); const [, year, month] = match; validatePeriod(year, month); await request("list", { year, month, page: "1" }); return { status: "connected", connected: true, message: "Koneksi Olsera tersedia." }; } catch (error) { const safe = error instanceof FinancialClientError ? error.safe : { status: "unreachable", message: "Tidak dapat terhubung ke server Olsera." }; return { ...safe, connected: false }; } }
export const getBalanceSheet = (period: string) => request("balancenew", { period, transaction: "0", store_id: ensureConfig().storeId });
export const getProfitLoss = (period: string) => request("gainloss", { period, transaction: "0", store_id: ensureConfig().storeId });
export const getCashFlow = (period: string) => request("cashflowstatement", { period, store_id: ensureConfig().storeId });
export const getLedgerSummary = (period: string) => request("ledger2", { period, store_id: ensureConfig().storeId });
export const getLedgerDetail = (period: string, accountCode: string, perPage = 5000) => request("ledger/detail", { period, store_id: ensureConfig().storeId, account_no: accountCode, sort_column: "transaction_date", sort_type: "asc", per_page: String(Math.min(Math.max(perPage, 1), 5000)) });
export async function getAccounts(year: number, month: number) { return Promise.all([request("list", { year: String(year), month: String(month), page: "1" }), request("list", { year: String(year), month: String(month), page: "2" })]); }
